import fs from 'fs';
import path from 'path';

import matter from 'gray-matter';

const CONTENT_DIR = path.join(process.cwd(), 'src/content/blog');

export type BlogCategory =
  | 'Build'
  | 'Integrate'
  | 'Ship'
  | 'Compare'
  | 'BYOK Files';

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  /** Optional search-optimized title used for the <title>/OG tag (falls back to title). */
  seoTitle?: string;
  /** Primary keyphrase the post targets; surfaced as the lead keyword. */
  focusKeyphrase?: string;
  date: string;
  dateModified?: string;
  author: string;
  tags: string[];
  readingTime: string;
  category: BlogCategory;
  coverImage?: string;
  faq?: Array<{ question: string; answer: string }>;
  content: string;
}

export type BlogPostMeta = Omit<BlogPost, 'content'>;

export function getAllPosts(): BlogPostMeta[] {
  if (!fs.existsSync(CONTENT_DIR)) {
    return [];
  }

  const files = fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith('.mdx'));

  return files
    .map((file) => {
      const slug = file.replace(/\.mdx$/, '');
      const raw = fs.readFileSync(path.join(CONTENT_DIR, file), 'utf-8');
      const { data } = matter(raw);
      return {
        slug,
        title: data.title as string,
        description: data.description as string,
        seoTitle: data.seoTitle as string | undefined,
        focusKeyphrase: data.focusKeyphrase as string | undefined,
        date: data.date as string,
        dateModified: data.dateModified as string | undefined,
        author: (data.author as string) ?? 'Bahroze Ali',
        tags: (data.tags as string[]) ?? [],
        readingTime: (data.readingTime as string) ?? '5 min read',
        category: (data.category as BlogCategory) ?? 'Build',
        coverImage: data.coverImage as string | undefined,
      };
    })
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getPostBySlug(slug: string): BlogPost | null {
  const filePath = path.join(CONTENT_DIR, `${slug}.mdx`);
  if (!fs.existsSync(filePath)) {
    return null;
  }

  const raw = fs.readFileSync(filePath, 'utf-8');
  const { data, content } = matter(raw);

  return {
    slug,
    title: data.title as string,
    description: data.description as string,
    seoTitle: data.seoTitle as string | undefined,
    focusKeyphrase: data.focusKeyphrase as string | undefined,
    date: data.date as string,
    dateModified: data.dateModified as string | undefined,
    author: (data.author as string) ?? 'Bahroze Ali',
    tags: (data.tags as string[]) ?? [],
    readingTime: (data.readingTime as string) ?? '5 min read',
    category: (data.category as BlogCategory) ?? 'Build',
    coverImage: data.coverImage as string | undefined,
    faq: data.faq as Array<{ question: string; answer: string }> | undefined,
    content,
  };
}

/**
 * Cover image URL for a post. Uses the post's `coverImage` (generated by the
 * local `npm run covers` script and committed to /public), falling back to the
 * site default OG image if a post hasn't had a cover generated yet.
 */
export function getCoverUrl(
  post: Pick<BlogPost, 'slug' | 'coverImage'>
): string {
  return post.coverImage ?? '/og-image.png';
}

/**
 * Renders a post as a clean, self-contained Markdown document for AI ingestion
 * (served at /{slug}.md and via `Accept: text/markdown`). FAQ lives in
 * frontmatter, so it's appended here to keep the markdown complete.
 */
export function postToMarkdown(post: BlogPost, baseUrl: string): string {
  const faq =
    post.faq && post.faq.length > 0
      ? '\n\n## FAQ\n\n' +
        post.faq.map((f) => `### ${f.question}\n\n${f.answer}`).join('\n\n')
      : '';

  return `# ${post.title}

> ${post.description}

Source: ${baseUrl}/${post.slug}
Published: ${post.date}${post.dateModified ? ` · Updated: ${post.dateModified}` : ''}
Author: ${post.author}

${post.content}${faq}
`;
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}
